
#+STARTUP: overview  //{overview, content, showall}

* Shortcuts
** Motion
C-c C-n
    Next heading. 
C-c C-p
    Previous heading. 
C-c C-f
    Next heading same level. 
C-c C-b
    Previous heading same level. 
C-c C-u
    Backward to higher level heading. 
** Edit Structure
M-RET
    Insert new heading with same level as current. If the cursor is in a plain list item, a new item is created (see Plain lists). When this command is used in the middle of a line, the line is split and the rest of the line becomes the new headline2.
M-S-RET
    Insert new TODO entry with same level as current heading. 
TAB in new, empty entry
    In a new entry with no text yet, TAB will cycle through reasonable levels. 
M-left/right
    Promote/demote current heading by one level. 
M-S-left/right
    Promote/demote the current subtree by one level. 
M-S-up/down
    Move subtree up/down (swap with previous/next subtree of same level). 
C-c C-w
    Refile entry or region to a different location. See Refile and copy. 
C-x n s/w
    Narrow buffer to current subtree / widen it again 
When there is an active region (Transient Mark mode), promotion and demotion work on all headlines in the region. 
    
** Sparse Trees
   C-c /
   This prompts for an extra key to select a sparse-tree creating command. 
   C-c / r
   Search. Prompts for a regexp and shows a sparse tree with all matches. Each match is also highlighted; the highlights disappear by pressing C-c C-c. 
** Lists
TAB
    Items can be folded just like headline levels. 
M-RET
    Insert new item at current level. With a prefix argument, force a new heading (see Structure editing). 
M-S-RET
    Insert a new item with a checkbox (see Checkboxes). 
M-S-up/down
    Move the item including subitems up/down (swap with previous/next item of same indentation). If the list is ordered, renumbering is automatic. 
M-left/M-right
    Decrease/increase the indentation of an item, leaving children alone. 
M-S-left/right
    Decrease/increase the indentation of the item, including subitems. 
C-c C-c
    If there is a checkbox (see Checkboxes) in the item line, toggle the state of the checkbox. Also verify bullets and indentation consistency in the whole list. 
C-c -
    Cycle the entire list level through the different itemize/enumerate bullets (‘-’, ‘+’, ‘*’, ‘1.’, ‘1)’). 
** Shortcuts
   C-c C-x f
   The footnote action command. When the cursor is on a footnote reference, jump to the definition. When it is at a definition, jump to the (first) reference. Otherwise, create a new footnote. When this command is called with a prefix argument, a menu of additional options including renumbering is offered.
   C-c C-c
   Jump between definition and reference. 


I left off at [[https://orgmode.org/guide/External-links.html#External-links][section 4.3]]

* Lists
{- + * 1. 1}
** example 
  LOTR example 
   1. The attack of the Rohirrim
   2. Eowyn's fight with the witch king
      * this was already my favorite scene in the book
      * I really like Miranda Otto.
      * [X] Checkbox
       	+ C-c C-c
   Important actors in this film are:
   - Elijah Wood :: He plays Frodo
     - Sean Astin :: He plays Sam, Frodo's friend.
* Footnotes
  This content has a footnote[fn:1]
** Shortcuts
   C-c C-x f
   The footnote action command. When the cursor is on a footnote reference, jump to the definition. When it is at a definition, jump to the (first) reference. Otherwise, create a new footnote. When this command is called with a prefix argument, a menu of additional options including renumbering is offered.
   C-c C-c
   Jump between definition and reference. 

[fn:1] A footnote!
* Tables
  + https://orgmode.org/guide/Tables.html#Tables
  + Spreadsheet-like calculations are supported in connection with the Emacs calc package
  + Use TAB

| Name | Phone | Age |
|------+-------+-----|
| Greg |  1234 |  28 |
| Erin |  4321 |  26 |
|      |       |     |
   
** Shortcuts
C-c |
    Convert the active region to table. If every line contains at least one TAB character, the function assumes that the material is tab separated. If every line contains a comma, comma-separated values (CSV) are assumed. If not, lines are split at whitespace into fields.
    If there is no active region, this command creates an empty Org table. But it’s easier just to start typing, like |Name|Phone|Age C-c RET.
C-c C-c
    Re-align the table without moving the cursor. 
TAB
    Re-align the table, move to the next field. Creates a new row if necessary. 
S-TAB
    Re-align, move to previous field. 
RET
    Re-align the table and move down to next row. Creates a new row if necessary.
M-left
M-right
    Move the current column left/right. 
M-S-left
    Kill the current column. 
M-S-right
    Insert a new column to the left of the cursor position. 
M-up
M-down
    Move the current row up/down. 
M-S-up
    Kill the current row or horizontal line. 
M-S-down
    Insert a new row above the current row. With a prefix argument, the line is created below the current one. 
C-c -
    Insert a horizontal line below current row. With a prefix argument, the line is created above the current line. 
C-c RET
    Insert a horizontal line below current row, and move the cursor into the row below that line. 
C-c ^
    Sort the table lines in the region. The position of point indicates the column to be used for sorting, and the range of lines is the range between the nearest horizontal separator lines, or the entire table.
* Hyperlinks
  [[]] []
  https://orgmode.org/guide/Link-format.html#Link-format
  [[https://orgmode.org/guide/Link-format.html#Link-format][same-hyperlink-with-description]]
** Internal Links
   If the link does not look like a URL, it is considered to be internal in the current file. 
   The most important case is a link like ‘[[#my-custom-id]]’ which will link to the entry with the CUSTOM_ID property ‘my-custom-id’. 

   [[target]]
   <<target>>

   [[Shortcuts]]

left off at [[https://orgmode.org/guide/External-links.html#External-links][section 4.3]]
