Taken from [[http://tuhdo.github.io/c-ide.html#sec-2][C/C++ Development Environment for Emacs]]

* Setting up ggtags

  Install GNU Global from your distribution's package manager (Linux / Mac) or from the Win32 port (Windows). If none is available, download the sources here and manually build the package. Do be aware that it is remotely possible that your package manager might install an outdated version that might impair some functionality of helm-gtags.
  Install ggtags. After installing ggtags from MELPA, add this code snippet to setup ggtags and key bindings:
  
  #+BEGIN_SRC
  (require 'ggtags)
  (add-hook 'c-mode-common-hook
  (lambda ()
  (when (derived-mode-p 'c-mode 'c++-mode 'java-mode 'asm-mode)
  (ggtags-mode 1))))
  
  (define-key ggtags-mode-map (kbd "C-c g s") 'ggtags-find-other-symbol)
  (define-key ggtags-mode-map (kbd "C-c g h") 'ggtags-view-tag-history)
  (define-key ggtags-mode-map (kbd "C-c g r") 'ggtags-find-reference)
  (define-key ggtags-mode-map (kbd "C-c g f") 'ggtags-find-file)
  (define-key ggtags-mode-map (kbd "C-c g c") 'ggtags-create-tags)
  (define-key ggtags-mode-map (kbd "C-c g u") 'ggtags-update-tags)
  
  (define-key ggtags-mode-map (kbd "M-,") 'pop-tag-mark)
  #+END_SRC
  
* Create a GTAGS database in project root 
  $ cd /path/to/project/root
  $ gtags

  After this, a few files are created:

  $ ls G*
  GPATH   GRTAGS  GTAGS
  
    GTAGS: definition database
    GRTAGS: reference database
    GPATH: path name database

  Creating GTAGS database with ggtags-create-tags; this is recommended way when using ggtags,
  to let it know where the project root is.
* Shorcuts 
  M-.
  Jump to definition or references.

  M-,
  Jump back.

  M-n  M-p
  Move back and forth over references.

  C-M-f
  runs forward-sexp, move forward over a balanced expression that can 
  be a pair or a symbol.

  C-M-b
  runs backward-sexp, move backward over a balanced expression that 
  can be a pair or a symbol. 

  C-M-k
  runs kill-sexp, kill balanced expression forward that can be a pair 
  or a symbol. 

  C-M-<SPC>
  runs mark-sexp, put mark after following expression 
  that can be a pair or a symbol. 
  
  C-M-a 
  runs beginning-of-defun, which moves point to beginning of a 
  function.

  C-M-e
  runs end-of-defun, which moves point to end of a function. 

  C-M-h 
  runs mark-defun, which put a region around whole current or 
  following function. 

* Basic concepts of tags
  A tag is a name of an entity in source code. An entity can be a variable, 
  a method definition, an include-operator… A tag contains information such 
  as name of the tag (the name of the variable, class, method), location of 
  this tag in source code and which file it belongs to. As an example, GNU 
  Global generates three tag databases:

    GTAGS: definition database
    GRTAGS: reference database
    GPATH: path name database
    
  A definition of a tag is where a tag is implemented. For example, a 
  function definition is the body where it is actually implemented, or a 
  variable definition is where the type and its property (i.e static) is 
  specified.
  
  A reference of a tag is where a tag is used in a source tree, but not where 
  it is defined.
* Find definitions in current buffer				      :imenu:
  The Imenu facility offers a way to find the major definitions, such as 
  function definitions, variable definitions in a file by name. ggtags can 
  integrate Imenu:
  
  (setq-local imenu-create-index-function #'ggtags-build-imenu-index)

  If you use Helm, use moo-jump-local from function-args package. You can 
  use it as an outline tree like in other IDEs.


* Emacs source tags
  sudo yum install emacs-el
  cd  /usr/share/emacs/24.3/lisp/
  sudo etags *.el.gz
